services:
  callio.api:
    image: callio.api
    build:
      context: .
      dockerfile: src/Callio.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      TenantProvisioning__VectorStoreProvider: AzureCosmos
      TenantProvisioning__BlobStorageProvider: AzureBlob
      TenantKnowledgeIngestion__BlobProvider: AzureBlob
      TenantKnowledgeIngestion__EmbeddingProvider: OpenAI
      TenantGeneration__CompletionProvider: OpenAI

  callio.admin:
    image: callio.admin
    build:
      context: .
      dockerfile: src/Callio.Admin/Dockerfile

  callio:
    image: callio
    build:
      context: .
      dockerfile: src/Callio/Callio/Dockerfile

  callio.client:
    image: callio.client
    build:
      context: .
      dockerfile: src/Callio/Callio.Client/Dockerfile

  callio-1:
    image: callio-1
    build:
      context: .
      dockerfile: src/Portal/Callio/Callio/Dockerfile

  callio.client-1:
    image: callio.client-1
    build:
      context: .
      dockerfile: src/Portal/Callio/Callio.Client/Dockerfile

